import type { Metadata } from "next";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

const player2 = Press_Start_2P( {
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Vax Blue Dawn",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${player2.className}`}
      >
        <video 
          className="fixed w-full h-full object-cover z-[-10]"
          autoPlay
          loop
          muted
          playsInline
          >
          <source src="/background.mp4" type="video/mp4"/>
        </video>
        {children}
      </body>
    </html>
  );
}
